import{a as g,i as p,S as h}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const b="46834340-89d4e2966326dbab6749c20a4",x="https://pixabay.com/api/";async function u(e,o=1,a=15){try{const t=await g.get(x,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a}});return t.data.hits.length===0&&p.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",maxWidth:"250px",color:"rgb(255, 162, 0)"}),t.data}catch(t){console.log("Error fetching images:",t),p.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"center",maxWidth:"250px",color:"rgb(255, 0, 0)"})}}let v=new h(".gallery a",{captionsData:"alt",captionDelay:250,animationSpeed:300,loop:!0});async function f(e){const o=document.querySelector(".gallery"),a=e.map(t=>`
          <div class="gallery-item">
            <ul class='ul-gallery'>
              <li class='li-gallery'>
                <a href='${t.largeImageURL}' data-lightbox='gallery'>
                  <img class="images" src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
                </a>
                <div class="info">
                  <p class="info-info"><span class="info-p">Likes:</span> ${t.likes}</p>
                  <p class="info-info"><span class="info-p">Views:</span> ${t.views}</p>
                  <p class="info-info"><span class="info-p">Comments:</span> ${t.comments}</p>
                  <p class="info-info"><span class="info-p">Downloads:</span> ${t.downloads}</p>
                </div>
              </li>
            </ul>
          </div>`).join("");o.innerHTML+=a,v.refresh(),L()}function L(){const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}function S(){document.querySelector(".gallery").innerHTML=""}const q=document.querySelector("#search-form"),w=document.querySelector("#search-input"),d=document.querySelector(".loader"),m=document.querySelector(".loaderr"),y=document.querySelector(".down_loader"),E=document.querySelector(".btn"),n=document.querySelector("#load-more-btn");let l=1,i="";E.addEventListener("click",async e=>{e.preventDefault(),i=w.value.trim(),d.style.display="flex",m.style.display="flex",i||iziToast.info({title:"End of results",message:"Введите значения!!!!!",position:"center",maxWidth:"250px",color:"rgb(255, 162, 0)"})});q.addEventListener("submit",async e=>{e.preventDefault(),l=1,S(),n.style.display="none",d.style.display="flex",m.style.display="flex";try{const o=await u(i,l);f(o.hits),o.totalHits>15&&(n.style.display="flex")}catch(o){console.error("Error during search:",o)}finally{d.style.display="none"}});n.addEventListener("click",async()=>{l+=1,y.style.display="flex",n.style.display="none";try{const e=await u(i,l);f(e.hits),l*15>=e.totalHits&&(n.style.display="none",iziToast.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"center",maxWidth:"250px",color:"rgb(255, 162, 0)"}))}catch(e){console.error("Error during load more:",e)}finally{y.style.display="none"}});
//# sourceMappingURL=index.js.map
